version: '3'
name: prod
services:
  backend-service:
    build:
      context: ./backend
      args:
        NODE_ENV: production
    container_name: ${BACKEND_APP_NAME}-backend
    ports:
      - "${PROD_BACKEND_PORT}:${PROD_BACKEND_PORT}"
    env_file:
      - ./backend/config/.env.production.local
    environment:
      - PORT=${PROD_BACKEND_PORT}
      - NODE_ENV=production
    command: npm start
    tty: true
